import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "next-themes";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import Navbar from "@/components/app_components/Navbar";
import SideBar from "@/components/app_components/sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import NextTopLoader from 'nextjs-toploader';
import LogSignature from "@/components/ui/Log";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    authors: [
        { name: "iheb mejri", url: "https://github.com/iheb1919" }
    ],
    publisher: "iheb mejri",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth.api.getSession({ headers: await headers() });
    if (!session) {
        redirect("/login");
    }
    return (
        <html
            suppressHydrationWarning
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased light`}
        >
            <body className="m flex flex-col min-h-screen overflow-y-auto">
                <LogSignature />
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <NextTopLoader showSpinner={false} color="var(--primary)" />

                    <TooltipProvider>
                        <SidebarProvider>
                            <div className="flex flex-col h-screen  flex-1">
                                <Navbar />
                                <main className=" flex-1 ">
                                    <SideBar />
                                    {/* <SidebarTrigger /> */}
                                    <div className="mt-16 mainContainer">
                                        {children}

                                    </div>
                                </main>
                            </div>
                        </SidebarProvider>
                    </TooltipProvider>

                </ThemeProvider></body>
        </html>
    );
}
